### PR TITLE
Debugging Load/Save Persistence

### PR DESCRIPTION
**Pull request by Malcolmnixon**
This pull request improves the persistence mechanism by:
- Applying a standard "PersistentXXXX" naming convention to persistence objects
- Adding wrist UI for save and quit
- Adding Backpack, Toolbox and Shared Storage
- Moving all new/load/save game logic to GameState
- Introducing PersistentConfig resource for standard game settings
- Switched to notifications for storage events

Note: After discussing with @DigitalN8m4r3 we found a simpler way of exposing the game settings. The game_state.tscn is added as a singleton with its populated properties. This lets the user edit its properties in the inspector:
image

### CODE REVIEW

**Comment by Malcolmnixon** [comment]
I would like to consider a standard naming convention of "PersistentXXX" for objects:
- PersistentWorld
- PersistentItem
- PersistentItemType
- PersistentItemDatabase
- PersistentPocket
- PersistentZone
- PersistentZoneInfo
- PersistentZoneDatabase
- PersistentGameSettings

Additionally I've declared some custom notifications to trigger load-state, save-state, and destroy. These notifications are currently defined in three scripts, but should be moved to a single location:
- NOTIFICATION_WORLD_STATE_LOAD
- NOTIFICATION_WORLD_STATE_SAVE
- NOTIFICATION_WORLD_STATE_DESTROY

**Comment by DigitalN8m4r3** [comment]
lgtm
gotta say, incredible work @Malcolmnixon

**Comment by BastiaanOlij** [comment]
> Note: After discussing with @DigitalN8m4r3 we found a simpler way of exposing the game settings. The game_state.tscn is added as a singleton with its populated properties. This lets the user edit its properties in the inspector:

I did not know you had access to that, that is super cool!

**Review by BastiaanOlij — APPROVED** [review]
This looks really good to me! Make sure not to loose any changes we need to apply upstream to godot-xr-tools.

Excellent stuff mate!

**Pull request merged**
